name: demo-kotlin  # Workflow name

on:      #Trigger when there is push or pull_request on main branch
  push:
    branches: [main, feature ]
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:    # jobs
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "hello world"

      - name: run a custom script
        run: |
          ls -la
          uptime      
      - name: run a multi-line script
        run: |
          echo "add other action to build"
          echo "testing"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Check java Version
        run: java --version
      - name: gradle build
        run: gradle build
      - name: docker version
        run: docker info
    
